### ISSUE TITLE
Make error : ITKLabelGeometryImageFilter.h not found

### ISSUE THREAD

**Issue by abhijithchunduru** [taznux/radiomics-tools#10]
Hi, 
When I tried to super-build the project, I get an error "ITKLabelGeometryImageFilter.h not found". I checked online and found that ITKLabelGeometryImageFilter is in review and the flag -DITK_USE_REVIEW=ON should be set during cmake of ITK. Despite doing this, I am not able to build the code. Please help

**Comment by taznux** [comment]
Sorry for the late reply! Which system did you use? I only tested on ubuntu linux, OSX and windows 7.

**Comment by abhijithchunduru** [comment]
Hi taznux, I had used Ubuntu 14.04 to build the code

**Comment by taznux** [comment]
I tested on the same version of Ubuntu and the flag was already set in the code. However, I did not specify ITK_DIR at building my codes at the superbuild script. If you have another ITK build, it makes problem. Please try the attached script.
[super-build.sh.txt](https://github.com/taznux/radiomics-tools/files/674583/super-build.sh.txt)

I specified ITK_DIR as ITK path in the superbuild as like below.

`cmake ${PROJECT_DIR} && make`  
to
`cmake ${PROJECT_DIR} -DITK_DIR=${ITK_BUILD_DIR} && make`

Thanks,
Wookjin

**Comment by taznux** [comment]
I tested Commit 1bab0d1 on Ubuntu 14.04. The environment would be similar to your case. https://travis-ci.org/taznux/radiomics-tools/jobs/187099778

**Comment by abhijithchunduru** [comment]
I got it working by setting -DModule_itkreview=on and -ditk_use_review=off in the super-build.sh

**Comment by taznux** [comment]
I found this link.
https://itk.org/migrationv4/index.php?action=artikel&cat=3&id=148&artlang=en
So, setting -DModule_ITKReview=on without -ditk_use_review is enough.
